apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: get-pods
subjects:
# Puedo especificar mas de un subject
- kind: User
  name: allfait # el nombre del usuario "no" del contexto
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role 
  name: get-pod # Especificamos el rol que queremos usar
  apiGroup: rbac.authorization.k8s.io
